name       : libgit2
version    : 0.28.5
release    : 27
source     :
    - https://github.com/libgit2/libgit2/releases/download/v0.28.5/libgit2-0.28.5.tar.gz : 2b7b68aee6f123bc84cc502a9c12738435b8054e7d628962e091cd2a25be4f42
license    : GPL-2.0
component  : programming.library
summary    : libgit2 is a portable, pure C implementation of the Git core methods.
description: |
    libgit2 is a portable, pure C implementation of the Git core methods.
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(libssh2)
    - pkgconfig(openssl)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
