name       : libgit2
version    : 0.26.7
release    : 24
source     :
    - https://github.com/libgit2/libgit2/archive/v0.26.7.tar.gz : 65584ac1f4de2c3ab8491351c8629eb68bad2d65e67f6411bf0333b8976dc4ef
license    : GPL-2.0
component  : programming.library
summary    : libgit2 is a portable, pure C implementation of the Git core methods.
description: |
    libgit2 is a portable, pure C implementation of the Git core methods.
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(libssh2)
    - pkgconfig(openssl)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
