name       : libgit2
version    : 0.24.6
release    : 19
source     :
    - https://github.com/libgit2/libgit2/archive/v0.24.6.tar.gz : 7b441a96967ff525e790f8b66859faba5c6be4c347124011f536ae9075ebc30c
license    : GPL-2.0
component  : programming.library
summary    : libgit2 is a portable, pure C implementation of the Git core methods.
description: |
    libgit2 is a portable, pure C implementation of the Git core methods.
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(libssh2)
    - pkgconfig(openssl)
build      : |
    %cmake .
install    : |
    %make_install
