name       : libgit2
version    : 0.28.3
release    : 25
source     :
    - https://github.com/libgit2/libgit2/archive/v0.28.3.tar.gz : ee5344730fe11ce7c86646e19c2d257757be293f5a567548d398fb3af8b8e53b
license    : GPL-2.0
component  : programming.library
summary    : libgit2 is a portable, pure C implementation of the Git core methods.
description: |
    libgit2 is a portable, pure C implementation of the Git core methods.
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(libssh2)
    - pkgconfig(openssl)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
