name       : libgit2
version    : 0.24.1
release    : 17
source     :
    - https://github.com/libgit2/libgit2/archive/v0.24.1.tar.gz : 60198cbb34066b9b5c1613d15c0479f6cd25f4aef42f7ec515cd1cc13a77fede
license    : GPL-2.0
component  : programming.library
summary    : libgit2 is a portable, pure C implementation of the Git core methods.
description: |
    libgit2 is a portable, pure C implementation of the Git core methods.
builddeps  :
    - pkgconfig(libssh2)
    - pkgconfig(openssl)
build      : |
    %cmake .
install    : |
    %make_install
