name       : libgit2
version    : 0.23.4
release    : 15
source     :
    - https://github.com/libgit2/libgit2/archive/v0.23.4.tar.gz : c7f5e2d7381dbc4d7e878013d14f9993ae8a41bd23f032718e39ffba57894029
license    : GPL-2.0
summary    : libgit2 is a portable, pure C implementation of the Git core methods.
description: |
    libgit2 is a portable, pure C implementation of the Git core methods.
libsplit : no
builddeps  :
    - pkgconfig(libssh2)
    - pkgconfig(openssl)
build      : |
    %cmake .
install  : |
    %make_install
