name       : libgit2
version    : 0.24.3
release    : 18
source     :
    - https://github.com/libgit2/libgit2/archive/v0.24.3.tar.gz : 0a24e6a51dbf3beecb0ebcd2cafb1e09b1212e910be6477b5de03c84a5586754
license    : GPL-2.0
component  : programming.library
summary    : libgit2 is a portable, pure C implementation of the Git core methods.
description: |
    libgit2 is a portable, pure C implementation of the Git core methods.
builddeps  :
    - pkgconfig(libssh2)
    - pkgconfig(openssl)
build      : |
    %cmake .
install    : |
    %make_install
