name       : libgit2
version    : 0.26.0
release    : 22
source     :
    - https://github.com/libgit2/libgit2/archive/v0.26.0.tar.gz : 6a62393e0ceb37d02fe0d5707713f504e7acac9006ef33da1e88960bd78b6eac
license    : GPL-2.0
component  : programming.library
summary    : libgit2 is a portable, pure C implementation of the Git core methods.
description: |
    libgit2 is a portable, pure C implementation of the Git core methods.
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(libssh2)
    - pkgconfig(openssl)
build      : |
    %cmake .
install    : |
    %make_install
