name       : libgit2
version    : 0.23.2
release    : 14
source     :
    - https://github.com/libgit2/libgit2/archive/v0.23.2.tar.gz : 20c0a6ee92c0e19207dac6ddc336b4ae4a1c4ddf91be0891e4b6e6ccba16df0b
license    : GPL-2.0
summary    : libgit2 is a portable, pure C implementation of the Git core methods.
description: |
    libgit2 is a portable, pure C implementation of the Git core methods.
libsplit : no
builddeps  :
    - pkgconfig(libssh2)
    - pkgconfig(openssl)
build      : |
    %cmake .
install  : |
    %make_install
