name       : libgit2
version    : 0.26.5
release    : 23
source     :
    - https://github.com/libgit2/libgit2/archive/v0.26.5.tar.gz : 52e28a5166564bc4365a2e4112f5e5c6e334708dbf13596241b2fd34efc1b0a9
license    : GPL-2.0
component  : programming.library
summary    : libgit2 is a portable, pure C implementation of the Git core methods.
description: |
    libgit2 is a portable, pure C implementation of the Git core methods.
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(libssh2)
    - pkgconfig(openssl)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
