name       :  libgit2
version    : 0.22.3
release    : 8
source     :
    - https://github.com/libgit2/libgit2/archive/v0.22.3.tar.gz : 511fe60e7c12c3525b4e0489861e5c1fe0e331d604bee9a3dfb8420c2f288f60
license    : GPL-2.0
summary    : libgit2 is a portable, pure C implementation of the Git core methods.
description: |
    libgit2 is a portable, pure C implementation of the Git core methods.
libsplit : no
builddeps  :
    - pkgconfig(libssh2)
    - pkgconfig(openssl)
build      : |
    %cmake -DTHREADSAFE:BOOL=ON .
    %make
install  : |
    %make_install
