name       :  libgit2
version    : 0.22.2
release    : 1
source     :
    - https://github.com/libgit2/libgit2/archive/v0.22.2.tar.gz : 3109f2579180d561fc736bad8bd917d7241477aab11633755c8a273beac53cdc
license    : GPL-2.0
summary    : libgit2 is a portable, pure C implementation of the Git core methods.
description: |
    libgit2 is a portable, pure C implementation of the Git core methods.
builddeps  :
  - libpth
  - pkgconfig(openssl)
build      : |
    install -d ./usr/bin/
    install -d .%libdir%
    install -d ./usr/include/
    %cmake . -DCBIN_INSTALL_DIR=./usr/bin -DCLIB_INSTALL_DIR=./%libdir% -DCINCLUDE_INSTALL_DIR=./usr/include
    %make
install  : |
    %make_install
