name       :  libgit2
version    : 0.23.0
release    : 5
source     :
    - https://github.com/libgit2/libgit2/archive/v0.23.0.tar.gz : 49d75c601eb619481ecc0a79f3356cc26b89dfa646f2268e434d7b4c8d90c8a1
license    : GPL-2.0
summary    : libgit2 is a portable, pure C implementation of the Git core methods.
description: |
    libgit2 is a portable, pure C implementation of the Git core methods.
builddeps  :
  - pkgconfig(openssl)
build      : |
    %cmake .
    %make
install  : |
    %make_install
