name       : libgit2
version    : 0.25.1
release    : 20
source     :
    - https://github.com/libgit2/libgit2/archive/v0.25.1.tar.gz : 7ae8e699ff7ff9a1fa702249140ee31ea6fd556bf7968e84e38165870667bcb1
license    : GPL-2.0
component  : programming.library
summary    : libgit2 is a portable, pure C implementation of the Git core methods.
description: |
    libgit2 is a portable, pure C implementation of the Git core methods.
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(libssh2)
    - pkgconfig(openssl)
build      : |
    %cmake .
install    : |
    %make_install
