name       : libgit2
version    : 1.3.0
release    : 33
source     :
    - https://github.com/libgit2/libgit2/archive/refs/tags/v1.3.0.tar.gz : 192eeff84596ff09efb6b01835a066f2df7cd7985e0991c79595688e6b36444e
license    : GPL-2.0-or-later
component  : programming.library
summary    : libgit2 is a portable, pure C implementation of the Git core methods.
description: |
    libgit2 is a portable, pure C implementation of the Git core methods.
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(libpcre)
    - pkgconfig(libssh2)
    - pkgconfig(openssl)
setup      : |
    %cmake_ninja -DTHREADSAFE:BOOL=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
